{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n  +'1'\n  -1", "trace": "self = <testcase.case.test_case.TestLogin object at 0x103c53880>\n\n    @allure.story(\"密码错误\")\n    def test_login_failure(self):\n        with allure.step(\"输入用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"输入密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\nE             +'1'\nE             -1\n\ntestcase/case/test_case.py:17: AssertionError"}, "steps": [{"name": "输入用户名", "status": "passed", "start": 1649911862653, "stop": 1649911862653}, {"name": "输入密码", "status": "passed", "start": 1649911862653, "stop": 1649911862653}, {"name": "登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n  +'1'\n  -1\n", "trace": "  File \"/Users/pchu/PycharmProjects/pytest/testcase/case/test_case.py\", line 17, in test_login_failure\n    assert '1' == 1\n"}, "start": 1649911862653, "stop": 1649911862653}], "start": 1649911862653, "stop": 1649911862656, "uuid": "8148c26c-88a1-4cde-b5fe-38ee27691f2d", "historyId": "3d76a8c7c2f91b648dec1b8f414548ea", "testCaseId": "ecf1118cadb3ca6142fa72d684e875af", "fullName": "testcase.case.test_case.TestLogin#test_login_failure", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "密码错误"}, {"name": "parentSuite", "value": "testcase.case"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "bogon"}, {"name": "thread", "value": "3332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.case.test_case"}]}