Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1067c8bb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1067c9570>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1067c9720>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session
初始化driver异常!HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1067c9960>: Failed to establish a new connection: [Errno 61] Connection refused'))
打开APP
测试完成，关闭app
报告地址:/Users/hpc/pytest/reports/html/index.html
